/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Panels;

import beans.clientPojo;
import controller.functionTools;
import beans.rate_table_pojo;
import beans.size_entry_pojo;
import controller.rate_controller;
import java.awt.Font;
import java.awt.event.KeyEvent;
import java.text.DecimalFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ranjan
 */
public class clientRateManagementPanel extends javax.swing.JPanel {
    
    DefaultTableModel size_table_model, size_detail_table_model,companyTableModel;
    functionTools fnTools;
    rate_controller controller;
    rate_table_pojo pojo;
    size_entry_pojo s_pojo;
    clientPojo c_pojo;

    /**
     * Creates new form purchaseVouchrePanel
     */
    public clientRateManagementPanel() {
        initComponents();
        s_pojo = new size_entry_pojo();
        c_pojo = new clientPojo();
        txtDiscAmt.setEditable(true);
        fnTools = new functionTools();
        controller = new rate_controller();
        sizeTable.getTableHeader().setFont(new Font("SansSerif", Font.ITALIC, 16));
        clientRateTable.getTableHeader().setFont(new Font("SansSerif", Font.ITALIC, 16));
        companyTable.getTableHeader().setFont(new Font("SansSerif", Font.ITALIC, 16));
        
    }
    
    
    private void reset_details(){
        txtsize.setText("");
        txtNewRate.setText("");
        txtRate.setText("");
        txtDiscAmt.setText("0");
        txtDiscRate.setText("0");
        
    }

    

    private boolean validate_and_save_data(){
        if(txtsize.getText().isEmpty()){
         JOptionPane.showMessageDialog(null,"Enter Photo Size");
         txtsize.requestFocus();
         return false;
        }
       else if(txtRate.getText().isEmpty()){
         JOptionPane.showMessageDialog(null,"Enter Original Rate");
         txtRate.requestFocus();
         return false;
        }
        else if(txtCompanyName.getText().isEmpty()){
         JOptionPane.showMessageDialog(null,"Enter Company Name");
         txtCompanyName.requestFocus();
         return false;
        }
            return true;
    }
    
    private void calculateTotal(){
        String total = Double.toString(Double.parseDouble(txtRate.getText())-Double.parseDouble(txtDiscAmt.getText()));
        txtNewRate.setText(total);
               
    }
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        txtsize = new javax.swing.JTextField();
        txtRate = new javax.swing.JTextField();
        txtNewRate = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        sizeTable = new javax.swing.JTable();
        btnSubmit = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        txtCompanyName = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        companyTable = new javax.swing.JTable();
        jLabel21 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        txtDiscRate = new javax.swing.JTextField();
        txtDiscAmt = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        clientRateTable = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();

        setBackground(java.awt.Color.lightGray);
        setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jPanel4.setBackground(java.awt.Color.lightGray);
        jPanel4.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jPanel5.setBackground(java.awt.Color.darkGray);

        jLabel12.setBackground(java.awt.Color.darkGray);
        jLabel12.setFont(new java.awt.Font("Century Schoolbook L", 1, 24)); // NOI18N
        jLabel12.setForeground(java.awt.Color.white);
        jLabel12.setText("Item :");

        jLabel18.setBackground(java.awt.Color.darkGray);
        jLabel18.setFont(new java.awt.Font("Century Schoolbook L", 1, 24)); // NOI18N
        jLabel18.setForeground(java.awt.Color.white);
        jLabel18.setText("Rate :");

        jLabel20.setBackground(java.awt.Color.darkGray);
        jLabel20.setFont(new java.awt.Font("Century Schoolbook L", 1, 24)); // NOI18N
        jLabel20.setForeground(java.awt.Color.white);
        jLabel20.setText("New Rate :");

        txtsize.setBackground(java.awt.Color.darkGray);
        txtsize.setFont(new java.awt.Font("Century Schoolbook L", 0, 24)); // NOI18N
        txtsize.setForeground(java.awt.Color.white);
        txtsize.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtsize.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtsizeKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtsizeKeyReleased(evt);
            }
        });

        txtRate.setEditable(false);
        txtRate.setBackground(java.awt.Color.darkGray);
        txtRate.setFont(new java.awt.Font("Century Schoolbook L", 0, 24)); // NOI18N
        txtRate.setForeground(java.awt.Color.white);
        txtRate.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtRate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRateActionPerformed(evt);
            }
        });
        txtRate.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtRateKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtRateKeyReleased(evt);
            }
        });

        txtNewRate.setEditable(false);
        txtNewRate.setBackground(java.awt.Color.darkGray);
        txtNewRate.setFont(new java.awt.Font("Century Schoolbook L", 0, 24)); // NOI18N
        txtNewRate.setForeground(java.awt.Color.white);
        txtNewRate.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtNewRate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNewRateActionPerformed(evt);
            }
        });
        txtNewRate.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNewRateKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNewRateKeyReleased(evt);
            }
        });

        sizeTable.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        sizeTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Size"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        sizeTable.setRowHeight(24);
        sizeTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sizeTableMouseClicked(evt);
            }
        });
        sizeTable.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                sizeTableKeyPressed(evt);
            }
        });
        jScrollPane2.setViewportView(sizeTable);
        if (sizeTable.getColumnModel().getColumnCount() > 0) {
            sizeTable.getColumnModel().getColumn(0).setResizable(false);
        }

        btnSubmit.setBackground(java.awt.Color.white);
        btnSubmit.setFont(new java.awt.Font("Century Schoolbook L", 1, 24)); // NOI18N
        btnSubmit.setForeground(java.awt.Color.darkGray);
        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        jLabel14.setBackground(java.awt.Color.darkGray);
        jLabel14.setFont(new java.awt.Font("Century Schoolbook L", 1, 24)); // NOI18N
        jLabel14.setForeground(java.awt.Color.white);
        jLabel14.setText("Company :");

        txtCompanyName.setBackground(java.awt.Color.darkGray);
        txtCompanyName.setFont(new java.awt.Font("Century Schoolbook L", 0, 24)); // NOI18N
        txtCompanyName.setForeground(java.awt.Color.white);
        txtCompanyName.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtCompanyName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCompanyNameFocusGained(evt);
            }
        });
        txtCompanyName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCompanyNameActionPerformed(evt);
            }
        });
        txtCompanyName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCompanyNameKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCompanyNameKeyReleased(evt);
            }
        });

        companyTable.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        companyTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Company Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        companyTable.setRowHeight(24);
        companyTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                companyTableMouseClicked(evt);
            }
        });
        companyTable.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                companyTableKeyPressed(evt);
            }
        });
        jScrollPane4.setViewportView(companyTable);

        jLabel21.setBackground(java.awt.Color.darkGray);
        jLabel21.setFont(new java.awt.Font("Century Schoolbook L", 1, 24)); // NOI18N
        jLabel21.setForeground(java.awt.Color.white);
        jLabel21.setText("Disc. % :");

        jLabel23.setBackground(java.awt.Color.darkGray);
        jLabel23.setFont(new java.awt.Font("Century Schoolbook L", 1, 24)); // NOI18N
        jLabel23.setForeground(java.awt.Color.white);
        jLabel23.setText("Disc.Rs. :");

        txtDiscRate.setBackground(java.awt.Color.darkGray);
        txtDiscRate.setFont(new java.awt.Font("Century Schoolbook L", 0, 24)); // NOI18N
        txtDiscRate.setForeground(java.awt.Color.white);
        txtDiscRate.setText("0");
        txtDiscRate.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtDiscRate.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDiscRateFocusLost(evt);
            }
        });
        txtDiscRate.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDiscRateKeyTyped(evt);
            }
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtDiscRateKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDiscRateKeyReleased(evt);
            }
        });

        txtDiscAmt.setBackground(java.awt.Color.darkGray);
        txtDiscAmt.setFont(new java.awt.Font("Century Schoolbook L", 0, 24)); // NOI18N
        txtDiscAmt.setForeground(java.awt.Color.white);
        txtDiscAmt.setText("0");
        txtDiscAmt.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtDiscAmt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDiscAmtFocusLost(evt);
            }
        });
        txtDiscAmt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDiscAmtActionPerformed(evt);
            }
        });
        txtDiscAmt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDiscAmtKeyTyped(evt);
            }
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtDiscAmtKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDiscAmtKeyReleased(evt);
            }
        });

        clientRateTable.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        clientRateTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Company Name", "Size", "Rate"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        clientRateTable.setRowHeight(24);
        jScrollPane1.setViewportView(clientRateTable);
        if (clientRateTable.getColumnModel().getColumnCount() > 0) {
            clientRateTable.getColumnModel().getColumn(0).setResizable(false);
            clientRateTable.getColumnModel().getColumn(0).setPreferredWidth(15);
            clientRateTable.getColumnModel().getColumn(1).setResizable(false);
            clientRateTable.getColumnModel().getColumn(1).setPreferredWidth(100);
            clientRateTable.getColumnModel().getColumn(2).setResizable(false);
            clientRateTable.getColumnModel().getColumn(3).setResizable(false);
            clientRateTable.getColumnModel().getColumn(3).setPreferredWidth(15);
        }

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addComponent(jLabel14)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtCompanyName))
                                    .addComponent(jScrollPane4))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                        .addComponent(jLabel12)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtsize, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtRate, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtDiscAmt, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtDiscRate, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(45, 45, 45)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtNewRate, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(btnSubmit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jScrollPane1))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator1)))
                .addContainerGap())
        );

        jPanel5Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtDiscAmt, txtDiscRate});

        jPanel5Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel20, txtNewRate});

        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(txtCompanyName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtsize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(12, 12, 12)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtRate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtDiscRate, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtDiscAmt, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNewRate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 23, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel5Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel12, jLabel14, jLabel18, jLabel20, txtCompanyName, txtsize});

        jPanel5Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {txtDiscAmt, txtDiscRate, txtNewRate, txtRate});

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
       pojo = new rate_table_pojo();
       pojo.setRate(Double.parseDouble(txtNewRate.getText()));
       pojo.setSize_id(s_pojo);
       String sql = "from clientPojo where company_name ='"+txtCompanyName.getText()+"'";
       c_pojo = controller.get_client(sql);
       pojo.setClient_id(c_pojo);
       if(validate_and_save_data()){
       controller.register_detail(pojo);
       controller.fill_detils(clientRateTable);
       reset_details();
       txtsize.requestFocus();
       }
        
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void sizeTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sizeTableMouseClicked
       
    }//GEN-LAST:event_sizeTableMouseClicked

    private void txtsizeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtsizeKeyReleased
        String sql = "from size_entry_pojo as s where s.size like '"+txtsize.getText()+"%'";
        controller.fill_size_name(sizeTable, sql);
    }//GEN-LAST:event_txtsizeKeyReleased

    private void txtRateKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRateKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRateKeyReleased

    private void txtNewRateKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNewRateKeyReleased
          
    }//GEN-LAST:event_txtNewRateKeyReleased

    private void txtRateKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRateKeyPressed
        int key = evt.getKeyCode();
        if ((key >= KeyEvent.VK_0 && key <= KeyEvent.VK_9) || (key >= KeyEvent.VK_NUMPAD0 && key <= KeyEvent.VK_NUMPAD9) || (key == KeyEvent.VK_BACK_SPACE)) {
          }
        else if ((key == KeyEvent.VK_ENTER)&&(!txtRate.getText().isEmpty())) {
            txtNewRate.requestFocus();
        }
        else {
            evt.consume();
            JOptionPane.showMessageDialog(null, "INVALID INSERT");
            txtRate.setText("");
        }
    }//GEN-LAST:event_txtRateKeyPressed

    private void txtNewRateKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNewRateKeyPressed
       int key = evt.getKeyCode();
        if ((key >= KeyEvent.VK_0 && key <= KeyEvent.VK_9) || (key >= KeyEvent.VK_NUMPAD0 && key <= KeyEvent.VK_NUMPAD9) || (key == KeyEvent.VK_BACK_SPACE)) {
            
        }
        else if ((key == KeyEvent.VK_ENTER)&&(!txtNewRate.getText().isEmpty())) {
            btnSubmit.requestFocus();
        }
        else {
            evt.consume();
            JOptionPane.showMessageDialog(null, "INVALID INSERT");
            txtNewRate.setText("");
        }
    }//GEN-LAST:event_txtNewRateKeyPressed

    private void txtsizeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtsizeKeyPressed
       int key = evt.getKeyCode();
        
       if ((key == KeyEvent.VK_ENTER)&&(!txtsize.getText().isEmpty())) {
            
            if(!fnTools.isEmpty(sizeTable)){
                size_table_model  =(DefaultTableModel)sizeTable.getModel();
                String Name = size_table_model.getValueAt(0, 0).toString();
                txtsize.setText(Name);
                String sql = "from size_entry_pojo where size ='"+txtsize.getText()+"'";
                s_pojo = controller.get_size(sql);
                txtRate.setText(Double.toString(s_pojo.getDisplay()));
                txtDiscRate.requestFocus();
        }
            
         }else if ((key == KeyEvent.VK_DOWN)) {
            if(!fnTools.isEmpty(sizeTable)){
            size_table_model  =(DefaultTableModel)sizeTable.getModel();
            sizeTable.setRowSelectionInterval(0, 0);
            sizeTable.requestFocus();
            
            }
            //txtRate.requestFocus();
        }else if (key == KeyEvent.VK_ESCAPE) {
            
            txtCompanyName.requestFocus();
            txtCompanyName.setText("");
        }
       
        
        
    }//GEN-LAST:event_txtsizeKeyPressed

    private void txtCompanyNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCompanyNameKeyPressed
        int key = evt.getKeyCode();
        if ((key == KeyEvent.VK_ENTER)&&(!txtCompanyName.getText().isEmpty())) {
         if(!fnTools.isEmpty(companyTable)){   
        companyTableModel  =(DefaultTableModel)companyTable.getModel();
        String Name = companyTableModel.getValueAt(0, 0).toString();
        txtCompanyName.setText(Name);
        txtsize.requestFocus();
        }
        }
        else if (key == KeyEvent.VK_DOWN) {
            if(!fnTools.isEmpty(companyTable)){
            companyTableModel  =(DefaultTableModel)companyTable.getModel();
            companyTable.setRowSelectionInterval(0, 0);
            companyTable.requestFocus();
            
            }
        }
    }//GEN-LAST:event_txtCompanyNameKeyPressed

    private void txtCompanyNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCompanyNameKeyReleased
        String value = txtCompanyName.getText();
        controller.fill_company_name(companyTable,value);
        
    }//GEN-LAST:event_txtCompanyNameKeyReleased

    private void companyTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_companyTableMouseClicked
        
    }//GEN-LAST:event_companyTableMouseClicked

    private void txtRateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRateActionPerformed

    private void txtCompanyNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCompanyNameFocusGained
        
    }//GEN-LAST:event_txtCompanyNameFocusGained

    private void txtDiscRateFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDiscRateFocusLost
        //jButton2FocusGained(evt);
    }//GEN-LAST:event_txtDiscRateFocusLost

    private void txtDiscRateKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDiscRateKeyTyped

    }//GEN-LAST:event_txtDiscRateKeyTyped

    private void txtDiscRateKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDiscRateKeyPressed
        int key = evt.getKeyCode();
        double total = 0;
        if ((key >= KeyEvent.VK_0 && key <= KeyEvent.VK_9) || (key >= KeyEvent.VK_NUMPAD0 && key <= KeyEvent.VK_NUMPAD9) || (key == KeyEvent.VK_BACK_SPACE)) {
            txtDiscRate.setEditable(true);
        }else if ((key == KeyEvent.VK_ENTER)&&(!"0".equals(txtDiscRate.getText()))&&(!txtDiscRate.getText().isEmpty())) {
            total = Double.parseDouble(txtRate.getText())*Double.parseDouble(txtDiscRate.getText())*0.01;
            txtDiscAmt.setText(new DecimalFormat("##.##").format(total));
            txtDiscAmt.setEditable(false);
            calculateTotal();
            btnSubmit.requestFocus();
        }else if ((key == KeyEvent.VK_ENTER)&&("0".equals(txtDiscRate.getText()))) {
            txtDiscAmt.setEditable(true);
            txtDiscAmt.requestFocus();
        } else {
            evt.consume();
            JOptionPane.showMessageDialog(null, "INVALID INSERT");
            txtDiscRate.setText("");
        }
    }//GEN-LAST:event_txtDiscRateKeyPressed

    private void txtDiscRateKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDiscRateKeyReleased

    }//GEN-LAST:event_txtDiscRateKeyReleased

    private void txtDiscAmtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDiscAmtFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDiscAmtFocusLost

    private void txtDiscAmtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDiscAmtKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDiscAmtKeyTyped

    private void txtDiscAmtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDiscAmtKeyPressed
        int key = evt.getKeyCode();
        if((key == KeyEvent.VK_ENTER)&&(!txtRate.getText().isEmpty())){
            calculateTotal();
            btnSubmit.requestFocus();
        }

    }//GEN-LAST:event_txtDiscAmtKeyPressed

    private void txtDiscAmtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDiscAmtKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDiscAmtKeyReleased

    private void companyTableKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_companyTableKeyPressed
        int key = evt.getKeyCode();
        if(key==KeyEvent.VK_ENTER){
            int row_index = companyTable.getSelectedRow();
            String value = companyTable.getModel().getValueAt(row_index,0).toString();
            txtCompanyName.setText(value);
            txtsize.requestFocus();
        }
    }//GEN-LAST:event_companyTableKeyPressed

    private void sizeTableKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sizeTableKeyPressed
        int key = evt.getKeyCode();
        if(key==KeyEvent.VK_ENTER){
            int row_index = sizeTable.getSelectedRow();
            String value = sizeTable.getModel().getValueAt(row_index,0).toString();
            txtsize.setText(value);
            txtsize.requestFocus();
        }
        
    }//GEN-LAST:event_sizeTableKeyPressed

    private void txtCompanyNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCompanyNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCompanyNameActionPerformed

    private void txtDiscAmtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDiscAmtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDiscAmtActionPerformed

    private void txtNewRateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNewRateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNewRateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSubmit;
    private javax.swing.JTable clientRateTable;
    private javax.swing.JTable companyTable;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable sizeTable;
    public javax.swing.JTextField txtCompanyName;
    private javax.swing.JTextField txtDiscAmt;
    private javax.swing.JTextField txtDiscRate;
    private javax.swing.JTextField txtNewRate;
    private javax.swing.JTextField txtRate;
    public javax.swing.JTextField txtsize;
    // End of variables declaration//GEN-END:variables
}
