/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Panels;


import Dao.DataBase_Connection;
import controller.Encryption;
import controller.login_controller;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import beans.log_in_pojo;

/**
 *
 * @author ranjan
 */
public class forgotPasswordPanel extends javax.swing.JPanel {
    protected Connection conInstance;
    protected Statement smtInstance;
    ResultSet rs;
    DataBase_Connection dao;
    log_in_pojo pojo;
    ImageIcon bi;
    login_controller controller;

    /**
     * Creates new form forgotPasswordPanel
     */
    public forgotPasswordPanel() {
        initComponents();
        dao = new DataBase_Connection();
        conInstance = dao.getConnection();
        pojo = new log_in_pojo();
        controller = new login_controller();
        submittButton.setEnabled(false);
        
    }
    
    public void reset(){
        txtUserName.setText("");
        pwdOldMasterPassword.setText("");
        pwdNewPassword.setText("");
        pwdConfirmNewPassword.setText("");
        submittButton.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        pwdOldMasterPassword = new javax.swing.JPasswordField();
        jLabel9 = new javax.swing.JLabel();
        pwdNewPassword = new javax.swing.JPasswordField();
        pwdConfirmNewPassword = new javax.swing.JPasswordField();
        jLabel10 = new javax.swing.JLabel();
        submittButton = new javax.swing.JButton();
        txtUserName = new javax.swing.JTextField();
        lblWarning = new javax.swing.JLabel();
        lblUserPwdNotification = new javax.swing.JLabel();

        jPanel2.setBackground(java.awt.SystemColor.control);
        jPanel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jLabel6.setFont(new java.awt.Font("Century Schoolbook L", 1, 24)); // NOI18N
        jLabel6.setText("Forgot Password ??");

        jLabel7.setFont(new java.awt.Font("Century Schoolbook L", 1, 24)); // NOI18N
        jLabel7.setText("Username :");

        jLabel8.setFont(new java.awt.Font("Century Schoolbook L", 1, 24)); // NOI18N
        jLabel8.setText("Master Password :");

        pwdOldMasterPassword.setFont(new java.awt.Font("Century Schoolbook L", 1, 24)); // NOI18N
        pwdOldMasterPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                pwdOldMasterPasswordKeyPressed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Century Schoolbook L", 1, 24)); // NOI18N
        jLabel9.setText("New Password :");

        pwdNewPassword.setFont(new java.awt.Font("Century Schoolbook L", 1, 24)); // NOI18N
        pwdNewPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                pwdNewPasswordKeyPressed(evt);
            }
        });

        pwdConfirmNewPassword.setFont(new java.awt.Font("Century Schoolbook L", 1, 24)); // NOI18N
        pwdConfirmNewPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                pwdConfirmNewPasswordFocusGained(evt);
            }
        });
        pwdConfirmNewPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                pwdConfirmNewPasswordKeyPressed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Century Schoolbook L", 1, 24)); // NOI18N
        jLabel10.setText("Confirm Password :");

        submittButton.setFont(new java.awt.Font("Century Schoolbook L", 1, 24)); // NOI18N
        submittButton.setText("Update");
        submittButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submittButtonActionPerformed(evt);
            }
        });

        txtUserName.setFont(new java.awt.Font("Century Schoolbook L", 1, 24)); // NOI18N
        txtUserName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtUserNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtUserNameFocusLost(evt);
            }
        });
        txtUserName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtUserNameKeyPressed(evt);
            }
        });

        lblWarning.setFont(new java.awt.Font("Century Schoolbook L", 1, 24)); // NOI18N

        lblUserPwdNotification.setFont(new java.awt.Font("Century Schoolbook L", 1, 24)); // NOI18N
        lblUserPwdNotification.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(jLabel6))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel9)
                                .addComponent(jLabel8))
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblWarning, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(pwdConfirmNewPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblUserPwdNotification, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(pwdNewPassword)
                            .addComponent(pwdOldMasterPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addComponent(submittButton, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(60, Short.MAX_VALUE))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {pwdConfirmNewPassword, pwdNewPassword, pwdOldMasterPassword, txtUserName});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel6)
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblWarning, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(pwdOldMasterPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(pwdNewPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel10)
                        .addComponent(pwdConfirmNewPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblUserPwdNotification, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(submittButton)
                .addGap(38, 38, 38))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    
    
    
    private void submittButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submittButtonActionPerformed
            pojo.setUserId(txtUserName.getText());
            pojo.setPassword(new String(pwdNewPassword.getPassword()));
            pojo.setCnfPassword(new String(pwdConfirmNewPassword.getPassword()));
            pojo.setMasterPassword(new String(pwdOldMasterPassword.getPassword()));
            
            controller.forgot(pojo);
            lblWarning.setIcon(null);
            txtUserName.requestFocus();
            reset();
            lblUserPwdNotification.setIcon(null);
 
    }//GEN-LAST:event_submittButtonActionPerformed

    private void txtUserNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUserNameFocusLost
        if(!txtUserName.getText().isEmpty()){
            pojo.setUserId(txtUserName.getText());
            if(!new login_controller().is_user_present(pojo)){
                bi = new ImageIcon(getClass().getResource("/BillingIcon/delete-filled.png"));
                submittButton.setEnabled(false);
            }
            else{
                bi = new ImageIcon(getClass().getResource("/BillingIcon/double-tick.png"));
                submittButton.setEnabled(true);
            }
        }
        else{
            
            txtUserName.requestFocus();

        }
        lblWarning.setIcon(bi);
    }//GEN-LAST:event_txtUserNameFocusLost

    private void txtUserNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUserNameKeyPressed
        int key = evt.getKeyCode();
        if ((key == KeyEvent.VK_ENTER)&&(!txtUserName.getText().isEmpty())) {
            pwdOldMasterPassword.requestFocus();
        }
    }//GEN-LAST:event_txtUserNameKeyPressed

    private void pwdOldMasterPasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pwdOldMasterPasswordKeyPressed
        int key = evt.getKeyCode();
        if ((key == KeyEvent.VK_ENTER)&&(pwdOldMasterPassword.getPassword().length>0)) {
            pwdNewPassword.requestFocus();
        }
    }//GEN-LAST:event_pwdOldMasterPasswordKeyPressed

    private void pwdNewPasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pwdNewPasswordKeyPressed
        int key = evt.getKeyCode();
        if ((key == KeyEvent.VK_ENTER)&&(pwdNewPassword.getPassword().length>0)) {
            pwdConfirmNewPassword.requestFocus();
        }
    }//GEN-LAST:event_pwdNewPasswordKeyPressed

    private void pwdConfirmNewPasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pwdConfirmNewPasswordKeyPressed
        int key = evt.getKeyCode();
        if ((key == KeyEvent.VK_ENTER)&&(pwdConfirmNewPassword.getPassword().length>0)) {
            
            String pass = new String (pwdNewPassword.getPassword());
            String pass1 = new String (pwdConfirmNewPassword.getPassword());
        if((pass.equals(pass1))){
            bi = new ImageIcon(getClass().getResource("/BillingIcon/double-tick.png"));
            if(new login_controller().is_user_present(pojo)){
                submittButton.setEnabled(true);
                submittButton.requestFocus();
            }
            else{
                JOptionPane.showMessageDialog(this, "Invalid User Id","Error",JOptionPane.ERROR_MESSAGE);
                txtUserName.requestFocus();
            }
            
        }else{
            bi = new ImageIcon(getClass().getResource("/BillingIcon/delete-filled.png"));
            submittButton.setEnabled(false);
            JOptionPane.showMessageDialog(this, "Password didnot match","Error",JOptionPane.ERROR_MESSAGE);
            pwdConfirmNewPassword.requestFocus();
        }
         
        lblUserPwdNotification.setIcon((Icon) bi);
        
        
        }
    }//GEN-LAST:event_pwdConfirmNewPasswordKeyPressed

    private void pwdConfirmNewPasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pwdConfirmNewPasswordFocusGained
        lblUserPwdNotification.setIcon(null);
    }//GEN-LAST:event_pwdConfirmNewPasswordFocusGained

    private void txtUserNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUserNameFocusGained
        lblWarning.setIcon(null);
    }//GEN-LAST:event_txtUserNameFocusGained


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblUserPwdNotification;
    private javax.swing.JLabel lblWarning;
    private javax.swing.JPasswordField pwdConfirmNewPassword;
    private javax.swing.JPasswordField pwdNewPassword;
    private javax.swing.JPasswordField pwdOldMasterPassword;
    private javax.swing.JButton submittButton;
    public javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables
}
