/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Panels;

import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;

/**
 *
 * @author idiotbox
 */
public class reportPanel extends javax.swing.JPanel {
    
    GridBagLayout layout = new GridBagLayout();
    clientReportPanel clientReport;
    GridBagConstraints gridBag;
    dailyReportPanel dailyReport;
    stockDetailPanel stockSummary;

    /**
     * Creates new form masterPanel
     */
    public reportPanel() {
        initComponents();
        displayPanel.setLayout(layout);
        init();
        addPanel();
        state();
        clientReport.setVisible(true);
        clientReport.txtCompanyName.requestFocus();
    }

    private void init() {
        gridBag = new GridBagConstraints();
        clientReport = new clientReportPanel();
        dailyReport = new dailyReportPanel();
        stockSummary = new stockDetailPanel();

    }

    private void addPanel() {
        displayPanel.add(clientReport, gridBag);
        displayPanel.add(dailyReport, gridBag);
        displayPanel.add(stockSummary, gridBag);

    }

    private void state() {
        
        clientReport.setVisible(false);
        dailyReport.setVisible(false);
        stockSummary.setVisible(false);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        displayPanel = new javax.swing.JPanel();
        dailyReportPanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        clientReportPanel = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        stockSummaryPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setBackground(java.awt.Color.gray);

        displayPanel.setBackground(java.awt.Color.lightGray);
        displayPanel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout displayPanelLayout = new javax.swing.GroupLayout(displayPanel);
        displayPanel.setLayout(displayPanelLayout);
        displayPanelLayout.setHorizontalGroup(
            displayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 912, Short.MAX_VALUE)
        );
        displayPanelLayout.setVerticalGroup(
            displayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        dailyReportPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dailyReportPanelMouseClicked(evt);
            }
        });
        dailyReportPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BillingIcon/icons8-report-card-60.png"))); // NOI18N
        dailyReportPanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 68, -1));

        jLabel5.setFont(new java.awt.Font("Century Schoolbook L", 1, 18)); // NOI18N
        jLabel5.setText("Daily");
        dailyReportPanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 70, -1));

        jLabel6.setFont(new java.awt.Font("Century Schoolbook L", 1, 18)); // NOI18N
        jLabel6.setText("Report");
        dailyReportPanel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 120, -1));

        clientReportPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clientReportPanelMouseClicked(evt);
            }
        });
        clientReportPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BillingIcon/icons8-profile-60.png"))); // NOI18N
        clientReportPanel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 68, -1));

        jLabel8.setFont(new java.awt.Font("Century Schoolbook L", 1, 18)); // NOI18N
        jLabel8.setText("Client ");
        clientReportPanel.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 70, -1));

        jLabel9.setFont(new java.awt.Font("Century Schoolbook L", 1, 18)); // NOI18N
        jLabel9.setText("Report");
        clientReportPanel.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 120, -1));

        stockSummaryPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                stockSummaryPanelMouseClicked(evt);
            }
        });
        stockSummaryPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BillingIcon/icons8-scan-stock-60.png"))); // NOI18N
        stockSummaryPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 68, -1));

        jLabel2.setFont(new java.awt.Font("Century Schoolbook L", 1, 18)); // NOI18N
        jLabel2.setText("Stock");
        stockSummaryPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 70, -1));

        jLabel3.setFont(new java.awt.Font("Century Schoolbook L", 1, 18)); // NOI18N
        jLabel3.setText("Summary");
        stockSummaryPanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 130, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dailyReportPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(stockSummaryPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(clientReportPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addComponent(displayPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(displayPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addComponent(clientReportPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(dailyReportPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(stockSummaryPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(119, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void clientReportPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clientReportPanelMouseClicked
        state();
        clientReport.setVisible(true);
       clientReport.txtCompanyName.requestFocus();
    }//GEN-LAST:event_clientReportPanelMouseClicked

    private void dailyReportPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dailyReportPanelMouseClicked
       state();
        dailyReport.setVisible(true);
    }//GEN-LAST:event_dailyReportPanelMouseClicked

    private void stockSummaryPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stockSummaryPanelMouseClicked
        state();
        stockSummary.setVisible(true);
        stockSummary.btnSearch.requestFocus();
    }//GEN-LAST:event_stockSummaryPanelMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel clientReportPanel;
    private javax.swing.JPanel dailyReportPanel;
    private javax.swing.JPanel displayPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel stockSummaryPanel;
    // End of variables declaration//GEN-END:variables
}
